spring.application.name=odontotrack

api.security.token.secret=cienciadacomputacao

# Configurações do Banco de Dados
#spring.datasource.url=jdbc:mysql://localhost:3306/odontotrack_db?createDatabaseIfNotExist=true
#spring.datasource.username=usuario
#spring.datasource.password=senha
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / o Hibernate criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do H2 (Banco em Memória)
spring.datasource.url=jdbc:h2:mem:odontodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 para voc� ver as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console